/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import Vocabulary.Dictionary;
import Vocabulary.Result;
import Vocabulary.Word;
import javax.swing.JOptionPane;

/**
 *
 * @author LeDuyHung
 */
public class editWord extends javax.swing.JFrame {

    /**
     * Creates new form editWord
     */
    Dictionary dic;
    
    public editWord(Dictionary dic, String StrTfWord, String StrTfMeaning, String StrTfCategory){
        this.dic = dic;
        initComponents();
        tfWord.setText(StrTfWord);
        tfMeaning.setText(StrTfMeaning);
        tfCategory.setText(StrTfCategory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbWord = new javax.swing.JLabel();
        lbMeaning = new javax.swing.JLabel();
        tfWord = new javax.swing.JTextField();
        tfMeaning = new javax.swing.JTextField();
        btEdit = new javax.swing.JButton();
        lbCategory = new javax.swing.JLabel();
        tfCategory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EditWord");
        setLocation(new java.awt.Point(430, 100));

        lbWord.setBackground(new java.awt.Color(153, 255, 153));
        lbWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord.setText("Word");
        lbWord.setOpaque(true);

        lbMeaning.setBackground(new java.awt.Color(153, 255, 153));
        lbMeaning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMeaning.setText("Meaning");
        lbMeaning.setOpaque(true);

        tfWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfWordMouseClicked(evt);
            }
        });

        tfMeaning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfMeaningMouseClicked(evt);
            }
        });

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        lbCategory.setBackground(new java.awt.Color(153, 255, 153));
        lbCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCategory.setText("Category");
        lbCategory.setOpaque(true);

        tfCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfCategoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMeaning, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMeaning, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(tfWord)
                    .addComponent(btEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCategory))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbWord, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMeaning, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMeaning, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(tfCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        Word word = new Word(tfWord.getText(), tfMeaning.getText(), tfCategory.getText());
        Result saveResult = dic.SaveWord(word);
        
        if(saveResult.IsSuccess){
            JOptionPane.showMessageDialog(rootPane, "Data have been edit !");
            btEdit.disable();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Cần nhập đầy đủ các thông tin");        }
    }//GEN-LAST:event_btEditActionPerformed

    private void tfWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfWordMouseClicked
        // TODO add your handling code here:
        tfWord.setText(null);
    }//GEN-LAST:event_tfWordMouseClicked

    private void tfMeaningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMeaningMouseClicked
        // TODO add your handling code here:
        tfMeaning.setText(null);
    }//GEN-LAST:event_tfMeaningMouseClicked

    private void tfCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCategoryMouseClicked
        // TODO add your handling code here:
        tfCategory.setText(null);
    }//GEN-LAST:event_tfCategoryMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdit;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbMeaning;
    private javax.swing.JLabel lbWord;
    private javax.swing.JTextField tfCategory;
    private javax.swing.JTextField tfMeaning;
    private javax.swing.JTextField tfWord;
    // End of variables declaration//GEN-END:variables
}
